#MANUAL DEFINITION OF INITIAL CONDITIONS.
#Set to 0 if you do NOT want to manually set them.
import numpy as np
import math

#Randomly generates location of transducers unless otherwise specified. Generated by first determining distance apart so probability of different distances more uniform.
def InitialLocations(location1, location2, radius):
    #If transducer location 1 specified
    if location1 == 0 and location2 != 0:
        location1 = np.random.randint(200, 800)
        if location1 <= 0:
            location1 = 1
    #If transducer location 2 specified
    elif location2 == 0 and location1 != 0:
        location2 = np.random.randint(1000, 1800)
        if location2 <= location1:
            location2 = location1 + 10
        if location2 >= 2000:
            location2 = 1999
    #If neither specified
    elif location1 == 0 and location2 == 0:
        distance = np.random.randint(1100, 1400)
        location1 = np.random.randint(radius+10, 1950 - distance)
        location2 = location1 + distance
    return [location1, location2]

#Randomly generates radius of turbulent structure
def InitialRadius(radius):
    if radius == 0:
        radius = np.random.randint(5, 150)
    return radius

#Randomly generates initial center coordinates of the turbulent structure.
def InitialCoords(radius):
    x = math.floor(np.random.randint(radius + 10, 450-radius))
    y = radius + 1
    if radius >= x:
        x = radius + 1
    if 500 - radius <= x:
        x = 500 - radius - 1
    return [x, y]
